version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: mego-post-db
    environment:
      POSTGRES_DB: "post"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis:/data
  golang-post:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mego-post-redis
    depends_on:
      - postgres
    ports:
      - "8080:8080"
